export const profile = {
  name: "Yves De Boeck",
  title: "Data & AI Engineer",
  tagline:
    "Building production-grade data platforms, cloud infrastructure, and AI systems that solve real industrial problems.",
  location: "Belgium",
  email: "yves.deboeck@ydb-solutions.com",
  github: "https://github.com/ydb-solutions",
  linkedin: "https://www.linkedin.com/in/yvesdeboeck",
  education: {
    degree: "MSc Computer Science Engineering (magna cum laude)",
    institution: "University of Antwerp",
    note: "Offered a PhD in AI/simulation for autonomous vehicles — chose industry to solve real-world problems.",
  },
};

export const experiences = [
  {
    company: "Atlas Copco",
    role: "Data & AI / Full Stack / Cloud Engineer",
    period: "Jan 2024 – Present",
    location: "Belgium",
    highlights: [
      "Designed and built a cloud-native IoT fleet management platform on Azure, ingesting real-time telemetry from industrial compressors worldwide via MQTT and IoT Hub, streamed live to the frontend via WebSockets.",
      "Wrote the embedded C++ component on a custom Yocto OS for compressor controllers, bridging the internal MQTT bus with the Azure IoT Hub.",
      "Built and maintained production APIs consumed by field service technicians on customer sites.",
      "Set up a Databricks data platform from scratch: medallion architecture, PySpark, dbt, Delta Lake, Unity Catalog, DLT — ingesting SQL, JSON, XML, Kafka, and text sources in batch and streaming.",
      "Developed a RAG-based internal knowledge app using Azure AI Search and Prompt Flow, deployed across multiple departments with per-department document indexes.",
      "Created an agentic AI assistant (similar to OpenClaw) using Azure Agent Framework (Semantic Kernel) and Azure AI Foundry, integrated with Slack — handling ticket management, PR reviews, security assessments, and CI/pipeline status reports.",
      "Built an agentic security scanner published as an Azure DevOps task: auto-detects stack, runs scanners, triages findings, fixes code in an agentic loop, and auto-generates a PR for final fixes.",
      "Full IaC with Bicep and Terraform across all projects; CI/CD with Azure DevOps and Jenkins.",
    ],
    tech: [
      "Python",
      "FastAPI",
      "React",
      "C++",
      "Yocto",
      "Databricks",
      "PySpark",
      "dbt",
      "Delta Lake",
      "Azure",
      "Bicep",
      "Terraform",
      "Azure DevOps",
      "Jenkins",
      "Docker",
      "MLflow",
      "Semantic Kernel",
      "Azure AI Foundry",
      "RAG",
      "MQTT",
      "IoT Hub",
    ],
  },
  {
    company: "TrinetX",
    role: "Software Engineer",
    period: "Sep 2021 – Dec 2023",
    location: "Ghent, Belgium",
    highlights: [
      "Full-stack development on a large-scale healthcare analytics platform (Java/Spring + React) used by hospital networks worldwide.",
      "Built ETL services in Python processing healthcare data across Vertica, Snowflake, Redis, and MongoDB.",
      "Designed and built a new observability service for ETL processes from scratch, including architecture decisions, CI/CD setup, and AWS cloud deployment.",
      "Operated in a strict TDD, SOLID, domain-driven design environment with Jenkins and GitLab CI.",
    ],
    tech: [
      "Java",
      "Spring Boot",
      "React",
      "Python",
      "Databricks",
      "Snowflake",
      "Vertica",
      "Redis",
      "MongoDB",
      "AWS",
      "Kubernetes",
      "Terraform",
      "Jenkins",
      "GitLab CI",
    ],
  },
  {
    company: "Essent",
    role: "AM Software Engineer – Billing Processes",
    period: "2020 – Sep 2021",
    location: "Belgium",
    highlights: [
      "Analysed and resolved issues across Java, PHP, and Python applications in a custom SAP billing ecosystem.",
      "Wrote complex PostgreSQL and MySQL queries to debug and fix billing logic, sharpening deep SQL expertise.",
    ],
    tech: ["Java", "PHP", "Python", "PostgreSQL", "MySQL", "AWS", "SOAP"],
  },
];

export const projects = [
  {
    name: "Space Insights",
    description:
      "Space data platform on Databricks running three live pipelines: NASA FIRMS thermal detections aggregated into H3 hexagons on a draggable globe, Sentinel-2 burn-scar detection over four monitored regions, and Mars rover telemetry anomaly detection scored against NASA's expert-labelled benchmark. Fully infrastructure-as-code, zero cloud cost.",
    tags: ["Databricks", "dbt", "Terraform", "PySpark", "MLflow", "H3", "MapLibre"],
    github: null,
    video: null,
    image: "/images/projects/space-insights.svg",
    writeup: "/blog/every-fire-on-earth",
    featured: true,
  },
  {
    name: "OpenClaw",
    description:
      "A self-hosted AI assistant I run in production on a GCP VM for my own workflow. The live system is organized around a long-lived gateway that owns sessions, tools, cron jobs, a browser control UI, and Telegram delivery, with all persistent state stored on disk and backed up nightly to GCS. Memory is file-first, with Markdown as the source of truth and SQLite-backed semantic recall layered on top. Inspired the agentic assistant I later built at Atlas Copco.",
    tags: ["AI Agents", "TypeScript", "Docker", "GCP", "Automation"],
    github: "https://github.com/ydb-solutions/openclaw",
    video: null,
    image: "/images/projects/openclaw.svg",
    writeup: "/blog/openclaw",
    featured: true,
  },
  {
    name: "Lens",
    description:
      "Lens is a stock intelligence platform that evaluates companies through five investor frameworks: Graham, Buffett, Lynch, O'Neil and Dividend. A FastAPI backend pulls fundamentals from Alpha Vantage and market data from Polygon, computes transparent weighted scores, and caches analyses in PostgreSQL. The React frontend visualises the result as a radar chart with per-profile metric breakdowns and optional AI commentary. Deployed on GCP with Terraform, Cloud Run, Cloud SQL and GitHub Actions CI/CD.",
    tags: ["FastAPI", "React", "PostgreSQL", "GCP", "Finance"],
    github: "https://github.com/ydb-solutions/lens",
    video: "/videos/lens-demo.mp4",
    image: "/images/projects/lens.svg",
    writeup: "/blog/lens",
    featured: true,
  },
  {
    name: "Memry",
    description:
      "Memry is my AI-powered study platform for turning PDFs, EPUBs, and even title-only book lookups into summaries, flashcards, and spaced-repetition review. The backend is a FastAPI service with pluggable LLM, storage, and notification layers; the product ships on both web and mobile. Runs on GCP with Terraform, Cloud Run, Cloud SQL, Cloud Storage, Cloud Scheduler, and GitHub Actions CI/CD via Workload Identity Federation.",
    tags: ["FastAPI", "React Native", "GCP", "LLM Systems"],
    github: "https://github.com/ydb-solutions/memry",
    video: null,
    image: "/images/projects/memry.svg",
    writeup: "/blog/memry",
    featured: true,
  },
  {
    name: "Finance App",
    description:
      "A local-first personal finance tracker built around bank statement ingestion rather than bank APIs. FastAPI handles Excel imports deterministically and uses GPT-assisted extraction for messy PDF statements, then a lightweight category-memory layer learns recurring merchants over time. Everything stays transparent with CSV/JSON storage and a simple review UI.",
    tags: ["FastAPI", "LLMs", "Personal Finance", "Data Modelling"],
    github: "https://github.com/ydb-solutions/finance_app",
    video: null,
    image: "/images/projects/finance-app.svg",
    writeup: "/blog/finance-app",
    featured: false,
  },
  {
    name: "IoT Fleet Management Platform",
    description:
      "Built an end-to-end fleet platform for industrial compressors spanning embedded software, cloud infrastructure, backend APIs, frontend dashboards, and data engineering. On the device side, I wrote the C++ bridge on Yocto Linux that translates the controller's internal MQTT bus into Azure IoT Hub telemetry, twins, and command flows. In the cloud, I worked on live WebSocket dashboards, remote actions, firmware rollout orchestration, and telemetry storage, with downstream Databricks pipelines feeding fleet analytics and reporting.",
    tags: ["Azure", "IoT", "C++", "Yocto", "FastAPI", "Databricks"],
    github: null,
    video: null,
    image: "/images/projects/iot-fleet-management-platform.svg",
    writeup: "/blog/iot-fleet-management-platform",
    featured: true,
    professional: true,
  },
  {
    name: "Model Predictive Control",
    description:
      "Built and productionised a cloud-side MPC stack for industrial compressors. The system combines per-site demand forecasting, mixed-integer optimisation, Databricks-based training and model serving, and a firmware bridge that turns cloud schedules into controller actions. I also worked across the secure device-provisioning path: temporary SAS bootstrap, mTLS certificate issuance, and automated cleanup once devices switch to certificate auth. The result was a control platform that treated latency, deployment safety, and device identity as first-class engineering problems.",
    tags: ["MLOps", "Databricks", "IoT", "Time Series", "C++", "Azure"],
    github: null,
    video: null,
    image: "/images/projects/model-predictive-control.svg",
    writeup: "/blog/model-predictive-control",
    featured: true,
    professional: true,
  },
  {
    name: "Agentic Security Scanner",
    description:
      "Azure DevOps security task that detects the project stack, orchestrates multiple scanners, and consolidates findings into one triage flow. An LLM enriches results with exploitability, recommended action, and false-positive filtering. For safe classes of issues it can propose fixes, validate them, and open a PR for human review — built for enterprise CI/CD where remediation speed matters as much as detection.",
    tags: ["Azure DevOps", "Security", "LLM Agents", "Python", "DevSecOps"],
    github: null,
    video: null,
    image: "/images/projects/agentic-security-scanner.svg",
    writeup: "/blog/agentic-security-scanner",
    featured: true,
    professional: true,
  },
  {
    name: "OpenCloud",
    description:
      "Internal team AI assistant for a large industrial company: Slack and Teams chat, Azure DevOps/Databricks/Microsoft 365 integrations via MCP sidecars, persistent team memory, scheduled reporting, and strong operational guardrails around what the agent is allowed to do autonomously.",
    tags: ["Python", "FastAPI", "Azure AI Foundry", "MCP", "Azure"],
    github: null,
    video: null,
    image: "/images/projects/opencloud.svg",
    writeup: "/blog/opencloud",
    featured: true,
    professional: true,
  },
  {
    name: "RAG Knowledge Assistant",
    description:
      "I built and deployed multiple department-specific knowledge assistants for a large industrial company. Each instance used its own Azure AI Search index over internal documents, with scheduled ingestion from systems like SharePoint and Atlassian, Prompt Flow orchestration, and grounded citations in the UI. The interesting engineering work was around multi-tenant isolation, hybrid retrieval quality, evaluation, and operational reliability rather than the chat surface itself.",
    tags: ["Python", "Azure AI Search", "Prompt Flow", "RAG", "Azure"],
    github: null,
    video: null,
    image: "/images/projects/rag-knowledge-assistant.svg",
    writeup: "/blog/rag-knowledge-assistant",
    featured: false,
    professional: true,
  },
  {
    name: "Databricks Data Platform",
    description:
      "Built a production Databricks data platform from scratch for a large industrial company, using a medallion architecture across SQL, JSON, XML, Kafka, and text-based sources. The platform combined PySpark, dbt, Delta Lake, Unity Catalog, and Delta Live Tables to support both batch and checkpointed streaming-style workloads, with governance and schema management treated as first-class design concerns from the start.",
    tags: ["Databricks", "PySpark", "dbt", "Delta Lake", "Azure", "Kafka"],
    github: null,
    video: null,
    image: "/images/projects/databricks-data-platform.svg",
    writeup: "/blog/databricks-data-platform",
    featured: false,
    professional: true,
  },
  {
    name: "Cloud4crc",
    description:
      "A professional FastAPI platform for technician desktop tools, combining file conversion, asynchronous uploads, device registration, and autotune APIs with dual v1/v2 contracts and Azure-native deployment. Much of the design is shaped by backward compatibility for clients that can't always update immediately, rather than by fashion.",
    tags: ["FastAPI", "Azure", "API Design", "Backwards Compatibility"],
    github: null,
    video: null,
    image: "/images/projects/cloud4crc.svg",
    writeup: "/blog/cloud4crc",
    featured: false,
    professional: true,
  },
];

export const skillGroups = [
  {
    category: "Languages",
    skills: ["Python", "SQL", "Java", "C++", "JavaScript / TypeScript", "Bash"],
  },
  {
    category: "Data Engineering",
    skills: [
      "Databricks",
      "Apache Spark / PySpark",
      "Delta Lake",
      "dbt",
      "Azure Data Factory",
      "Azure Data Explorer",
      "Kafka",
      "ETL/ELT (Batch & Streaming)",
      "Unity Catalog",
      "Snowflake",
    ],
  },
  {
    category: "AI / ML",
    skills: [
      "RAG Architecture",
      "LLM Agents",
      "Vector Databases",
      "MLflow",
      "Azure AI Foundry",
      "Semantic Kernel",
      "Prompt Flow",
      "NeuralProphet",
    ],
  },
  {
    category: "Cloud & Infrastructure",
    skills: [
      "Azure (Expert)",
      "GCP",
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Bicep",
      "Azure DevOps",
      "Jenkins",
      "IoT Hub",
    ],
  },
  {
    category: "Backend",
    skills: [
      "FastAPI",
      "Spring Boot",
      "Node.js",
      "PostgreSQL",
      "CosmosDB",
      "SQLAlchemy",
      "REST / WebSockets",
      "MQTT",
    ],
  },
  {
    category: "Frontend",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
  },
];

export const certifications = [
  {
    name: "Databricks Data Engineering Professional",
    issuer: "Databricks",
    tier: "professional",
    file: "/docs/databricks_data_engineer_professional_cert.pdf",
  },
  {
    name: "Databricks Data Engineering Associate",
    issuer: "Databricks",
    tier: "associate",
    file: "/docs/databricks_data_engineer_associate_cert.pdf",
  },
  {
    name: "Azure Data Engineer Associate (DP-203)",
    issuer: "Microsoft",
    tier: "associate",
    file: "/docs/microsoft_azure_data_engineer_associate_cert.pdf",
  },
  {
    name: "Azure AI Engineer Associate (AI-102)",
    issuer: "Microsoft",
    tier: "associate",
    file: "/docs/microsoft_azure_ai_engineer_associate_cert.pdf",
  },
  {
    name: "AWS Solutions Architect",
    issuer: "Amazon",
    tier: "associate",
    file: null,
  },
  {
    name: "Professional Scrum Master",
    issuer: "Scrum.org",
    tier: "professional",
    file: null,
  },
  {
    name: "Oracle Java SE 8 Professional",
    issuer: "Oracle",
    tier: "professional",
    file: null,
  },
  {
    name: "Certified Associate in Python",
    issuer: "Python Institute",
    tier: "associate",
    file: null,
  },
  {
    name: "Azure Fundamentals (AZ-900)",
    issuer: "Microsoft",
    tier: "fundamentals",
    file: null,
  },
  {
    name: "Azure Data Fundamentals (DP-900)",
    issuer: "Microsoft",
    tier: "fundamentals",
    file: null,
  },
  {
    name: "Azure AI Fundamentals (AI-900)",
    issuer: "Microsoft",
    tier: "fundamentals",
    file: null,
  },
];

export const education = [
  {
    degree: "MSc Computer Science Engineering (magna cum laude)",
    institution: "University of Antwerp",
    note: "Offered a PhD in AI/simulation for autonomous vehicles — chose industry to solve real-world problems.",
    file: "/docs/msc_diploma.pdf",
  },
];
